// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5lcmFcsr08OXqOSZcZiRqthqfRpYBLys',
    appId: '1:104302360213:web:5157d96d77c396683acd9c',
    messagingSenderId: '104302360213',
    projectId: 'fir-a4b5b',
    authDomain: 'fir-a4b5b.firebaseapp.com',
    storageBucket: 'fir-a4b5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUB1to5TSf9HKCnDbLpwhTIs62H5wDHw4',
    appId: '1:104302360213:android:f57dcbd144eb60ea3acd9c',
    messagingSenderId: '104302360213',
    projectId: 'fir-a4b5b',
    storageBucket: 'fir-a4b5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW4i7KK4hjjLEaIeFeHH4Le6p5N642MH4',
    appId: '1:104302360213:ios:e8e9303a1cd288ca3acd9c',
    messagingSenderId: '104302360213',
    projectId: 'fir-a4b5b',
    storageBucket: 'fir-a4b5b.appspot.com',
    iosBundleId: 'com.example.imagenesFlutter',
  );
}
